# Generated by Django 2.0.5 on 2018-05-25 18:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='ErdemDefault', max_length=64, verbose_name='First name')),
                ('avatar', models.ImageField(default='/static/images/avatar.png', upload_to='static/images/avatars')),
                ('surname', models.TextField(max_length=128, verbose_name='Family name')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('address_1', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='city')),
                ('zip_code', models.CharField(default='3123', max_length=5, verbose_name='zip code')),
                ('phone', models.TextField(blank=True, max_length=64, verbose_name='Phone')),
                ('username', models.ForeignKey(on_delete='CASCADE', related_name='username', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2018, 5, 26, 4, 37, 13, 263703))),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
