# Generated by Django 2.0.5 on 2018-05-25 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_auto_20180526_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 5, 6, 33, 974923)),
        ),
    ]
