# Generated by Django 2.0.5 on 2018-05-25 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shipping_first_name', models.CharField(max_length=50)),
                ('shipping_last_name', models.CharField(max_length=50)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_address', models.CharField(max_length=250)),
                ('shipping_landmark', models.CharField(max_length=250)),
                ('shipping_country', models.CharField(max_length=50)),
                ('shipping_state', models.CharField(max_length=50)),
                ('shipping_city', models.CharField(max_length=50)),
                ('shipping_postcode', models.CharField(max_length=50)),
                ('billing_first_name', models.CharField(max_length=50)),
                ('billing_last_name', models.CharField(max_length=50)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(max_length=250)),
                ('billing_landmark', models.CharField(max_length=250)),
                ('billing_country', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_postcode', models.CharField(max_length=50)),
                ('use_shipping_for_billing', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='purchases', to='coupons.Coupon')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='purchase_items', to='shop.Product')),
                ('purchase', models.ForeignKey(on_delete='CASCADE', related_name='items', to='purchases.Purchase')),
            ],
        ),
    ]
