# Generated by Django 2.0.5 on 2018-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='perpage',
            field=models.IntegerField(default=8),
        ),
    ]
